### ISSUE TITLE
[ CLOSED! ] - No midi devices showing up in flatpak version of Ardour (and UI is not working with rightclick after adding midi/audio track) 

### ISSUE THREAD

**Issue by ztealmax32** [flathub/org.ardour.Ardour#72]
I Cant get my midi keyboard to show up in ardour, it used to work beforewheni tried flatpak version of ardour  a couple of months ago
so i guess its updated and something changed? (It does show up in non flatpak version to be clear)

OS: Fedora 42 Gnome (Custom)
APP: org.ardour.Ardour (flatpak)
SETTTINGS: jack/pipewire
OVERRIDES:
```
sudo flatpak override org.ardour.Ardour --talk-name=org.gtk.vfs.* --filesystem=xdg-run/gvfs
sudo flatpak override org.ardour.Ardour --filesystem=/home/$USER
```
PACKAGES: pipewire-jack-audio-connection-kit

Really need help getting this up and running, all the help is appriciated (If you got it working with midi keyboard and it shows up for example, any tips are welcome)

```

**flatpak info --show-permissions org.ardour.Ardour**
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=all;
filesystems=home;xdg-run/pipewire-0;/home/ztealmax32;xdg-run/gvfs;

[Session Bus Policy]
org.freedesktop.ReserveDevice1.*=own
org.gtk.vfs.*=talk

[Environment]
LXVST_PATH=/app/extensions/Plugins/vst
TMPDIR=/var/tmp
ALSA_CONFIG_PATH=
VST3_PATH=/app/extensions/Plugins/vst3
LADSPA_PATH=/app/extensions/Plugins/ladspa:/app/lib/ladspa
GTK_THEME=Adwaita:dark
```

**Comment by ztealmax32** [comment]
** UPDATE**

I installed other flatpak DAW (Qtractor, Bitwig etc) they all worked with midi keyboard
the issue is with this ardour flatpak, im guessing you changed something or did something that made it not work anymore

also looks weird if you go in to  Ardour preferences midi dont look as it should missing borders etc.

![Image](https://github.com/user-attachments/assets/098a93e7-74b9-4a86-9628-054b75a0a477)

**Comment by runiq** [comment]
This issue probably occurs because Ardour was built against [a Pipewire version < 1.4](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/24.08/elements/components/pipewire-base.bst?ref_type=heads#L139). Pipewire 1.4 has added [support for MIDI 2](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/1.4.0), which still has some backwards compatibility issues, especially with older JACK clients. This particular issue was only [fixed a few days ago](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/564c9b1ba508f350b51a565c13c0cfc2ed2ea94f). Either your host system needs a Pipewire release that has the linked commit, or flatpaked Ardour needs to be rebuilt against Pipewire 1.4.x.

There is [a corresponding issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4712) on the Pipewire issue tracker.

**Comment by runiq** [comment]
For what it's worth, this has been fixed on Fedora with the (host) update Pipewire 1.4.4.

**Comment by ztealmax32** [comment]
@runiq Thank you i will have to install Fedora and test it out, appreciate the update, ill get back if it still is a issue :)

**Comment by ztealmax32** [comment]
@runiq It worked now i see midi keyboard, however still having this weird thing that i cant right click on midi track and get 
menu to select input or output devices im guessing its something thats updated thats putting a wrench in the ui. (it will work after about 30-40sec once, then it stops working with right click menu again, but to be fair im having same issue now on dnf installed package also so iguess it might be gtk thingy messing up?. any insights about what could be wrong?

**Comment by ztealmax32** [comment]
@runiq  **UPDATE 20250602 15:48**

Issues are sorted it wasnt only pipewire issue (that's been updated as you said runiq, i naroved it down to mutter issue, that has also now been updated, so all problems that was on both this flatpak version of ardour and the rpm based ardour is now sorted :)

All works as intended

//Thank you for you support
Ztealmax

**Comment by runiq** [comment]
Great to hear. You'll have to use the dedicated button for closing the thread, though -- adding '[ CLOSED! ]' to the title does not in fact close it.
